version: '3.1'
services:
  humhub:
    build: .
    links:
      - "db:db"
    ports:
      - "8080:80"
      - "465:465"
    environment:
      HUMHUB_DB_USER: root
      HUMHUB_DB_PASSWORD: root
      HUMHUB_AUTO_INSTALL: 0
      HUMHUB_DEBUG: 0
    volumes:
      - "/var/www/localhost/htdocs/protected/config:/var/www/localhost/htdocs/protected/config"
      - "/var/www/localhost/htdocs/uploads:/var/www/localhost/htdocs/uploads"
      - "/var/www/localhost/htdocs/protected/modules:/var/www/localhost/htdocs/protected/modules"
      - "/var/www/localhost/htdocs/protected/runtime:/var/www/localhost/htdocs/protected/runtime"
      - "/var/www/localhost/htdocs/assets:/var/www/localhost/htdocs/assets"
      - "/etc/humhub/themes/CubbyNet:/var/www/localhost/htdocs/themes/CubbyNet"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: humhub
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /var/lib/mysql:/var/lib/mysql
